stages:
  - build
  - test

image: ultimaker/cura-build-environment

buildSteSlicer:
  stage: build
  script:
    - docker/build.sh
  artifacts:
    paths:
      - build

testSteSlicer:
  stage: test
  script:
    - cd build
    - ctest3 --output-on-failure -T Test
