stages:
  - build
  - test

buildSteSlicer:
  image: ultimaker/cura-build-environment
  stage: build
  script:
    - docker/build.sh
  artifacts:
    paths:
      - build

extractTranslations:
  image: ultimaker/cura-build-environment
  stage: build
  script:
    - docker/extract-translations.sh
  artifacts:
    paths:
      - resources/i18n

testSteSlicer:
  image: ultimaker/cura-build-environment
  stage: test
  script:
    - docker/test.sh