stages:
  - build
  - test
  - deploy

buildSteSlicer:
  image: ultimaker/cura-build-environment
  stage: build
  script:
    - docker/build.sh
  artifacts:
    paths:
      - build

extractTranslations:
  image: ultimaker/cura-build-environment
  stage: build
  script:
    - docker/extract-translations.sh
  artifacts:
    paths:
      - resources/i18n

testSteSlicer:
  image: ultimaker/cura-build-environment
  stage: test
  script:
    - docker/test.sh

deployDeveloperBuild:
  stage: deploy
  script:
    - curl -X POST -F token=38fe74bf0215330816f969bdd3e555 -F ref=master https://gitlab.com/api/v4/projects/16067414/trigger/pipeline
  only:
    - schedules